sudo: required

services:
  - docker

before_install:
  - docker build -t python-images-test -f ubuntu18-python36.Dockerfile .

script:
  - docker run python-images-test /bin/bash -c "pdftoppm -v && tesseract --version"
  - docker images
